%% SCRIPT TO EXPORT 30-MINUTE VALUES

%% initialize
clearvars;

%% folders for loading and saving data
folder_LoadData = '../../AnalysisData/FluxLaw/'; %folder for retrieving data for this extraction
folder_SaveData = '../../AnalysisData/FluxLaw/'; %folder for storing outputs of this extraction
folder_Functions = '../Functions/'; %folder with functions

%% paths for loading and printing plots - restricted
LoadData_Path = strcat(folder_LoadData,'FluxLawCalcs_30min_Restricted'); %path for flux law calcs
ExportSummaryTable_PartialPath = strcat(folder_SaveData,'FluxLawCalcs_30min_Restricted'); %path for exporting summary table

%% load functions and window data
addpath(folder_Functions); %point MATLAB to location of functions
load(LoadData_Path); %load data windows

%% get site info
N_Sites = length(Sites);

%% CREATE AND EXPORT SUMMARY TABLE
for i = 1:N_Sites
    bin_N = bin_N_all{i};
    ust = ust_bin_avg_all{i};
    sigma_ust = ust_bin_sigma_all{i};
    tau = tau_bin_avg_all{i};
    sigma_tau = tau_bin_sigma_all{i};
    tauex = tauex_bin_avg_all{i};
    sigma_tauex = tauex_bin_sigma_all{i};
    zq = zq_bin_avg_all{i}; zq(isnan(zq))=0;
    sigma_zq = zq_bin_sigma_all{i}; sigma_zq(sigma_zq==Inf)=0;
    Q = Q_bin_avg_all{i};
    sigma_Q = Q_bin_sigma_all{i};
    Qhat = Qnorm_bin_avg_all{i};
    sigma_Qhat = Qnorm_bin_sigma_all{i};
    fQ = fQ_bin_avg_all{i};
    sigma_fQ = fQ_bin_sigma_all{i};

    %generate list of variables
    TableVars = ...
        {'bin_N',...
        'ust',...
        'sigma_ust',...
        'tau',...
        'sigma_tau',...
        'tauex',...
        'sigma_tauex',...
        'zq',...
        'sigma_zq',...
        'Q',...
        'sigma_Q',...
        'Qhat',...
        'sigma_Qhat',...
        'fQ',...
        'sigma_fQ'};
    N_Vars = length(TableVars);

    SummaryTable = table(...
        cellstr(int2str(bin_N)),...
        cellstr(num2str(ust,'%.3f')),...
        cellstr(num2str(sigma_ust,'%.3f')),...
        cellstr(num2str(tau,'%.3f')),...
        cellstr(num2str(sigma_tau,'%.3f')),...
        cellstr(num2str(tauex,'%.3f')),...
        cellstr(num2str(sigma_tauex,'%.3f')),...
        cellstr(num2str(zq,'%.3f')),...
        cellstr(num2str(sigma_zq,'%.3f')),...
        cellstr(num2str(Q,'%.2f')),...
        cellstr(num2str(sigma_Q,'%.2f')),...
        cellstr(num2str(Qhat,'%.3f')),...
        cellstr(num2str(sigma_Qhat,'%.3f')),...
        cellstr(num2str(fQ,'%.3f')),...
        cellstr(num2str(sigma_fQ,'%.3f')),...
        'VariableNames',TableVars);

    ExportData_Path = [ExportSummaryTable_PartialPath,'_',Sites{i},'.csv'];
    writetable(SummaryTable,ExportData_Path);
end