%% SCRIPT TO EXPORT 30-MINUTE VALUES

%% initialize
clearvars;

%% folders for loading and saving data
folder_ProcessedData = '../../../../Google Drive/Data/AeolianFieldwork/Processed/'; %folder for retrieving processed data
folder_WindowData = '../../AnalysisData/Windowing/'; %folder for retrieving processed data
folder_SaveData = '../../../../Google Drive/Data/AeolianFieldwork/Export/30 Minute/'; %folder for storing outputs of this extraction
folder_Functions = '../Functions/'; %folder with functions

%% information about where to load data and save plots - restricted windows
LoadWindowData_Path = strcat(folder_WindowData,'DataWindowCalcs_30min_Restricted'); %path for loading unbinned data
ExportSummaryTable_PartialPath = strcat(folder_WindowData,'SummaryTable_30min_Restricted'); %path for exporting summary table

% %% information about where to load data and save plots - unrestricted windows
% LoadWindowData_Path = strcat(folder_WindowData,'DataWindowCalcs_30min_Unrestricted'); %path for loading unbinned data
% ExportSummaryTable_PartialPath = strcat(folder_WindowData,'SummaryTable_30min_Unrestricted'); %path for exporting summary table

%% load functions and window data
addpath(folder_Functions); %point MATLAB to location of functions
load(LoadWindowData_Path); %load data windows

%% get site info
N_Sites = length(Sites);

%% CREATE AND EXPORT SUMMARY TABLE
for i = 1:N_Sites
    StartTimes = StartTimes_all{i};
    EndTimes = EndTimes_all{i};
    ust = ustRe_all{i};
    sigma_ust = sigma_ustRe_all{i};
    tau = tauRe_all{i};
    sigma_tau = sigma_tauRe_all{i};
    theta = theta_adjusted_all{i};
    zL = zL_all{i};
    zq = zq_all{i};
    sigma_zq = sigma_zq_all{i};
    Q = Q_all{i};
    sigma_Q = sigma_Q_all{i};
    fQ = fQ_all{i};

    %generate list of variables
    TableVars = ...
        {'Date',...
        'StartTime',...
        'EndTime',...
        'ust',...
        'sigma_ust',...
        'tau',...
        'sigma_tau',...
        'theta',...
        'zL',...
        'zq',...
        'sigma_zq',...
        'Q',...
        'sigma_Q',...
        'fQ'};
    N_Vars = length(TableVars);

    SummaryTable = table(...
        cellstr(datestr(StartTimes,'yyyy-mm-dd')),...
        cellstr(datestr(StartTimes,'HH:MM')),...
        cellstr(datestr(EndTimes,'HH:MM')),...
        cellstr(num2str(ust,'%.3f')),...
        cellstr(num2str(sigma_ust,'%.3f')),...
        cellstr(num2str(tau,'%.3f')),...
        cellstr(num2str(sigma_tau,'%.3f')),...
        cellstr(num2str(theta,'%.1f')),...
        cellstr(num2str(zL,'%.3f')),...
        cellstr(num2str(zq,'%.3f')),...
        cellstr(num2str(sigma_zq,'%.3f')),...
        cellstr(num2str(Q,'%.2f')),...
        cellstr(num2str(sigma_Q,'%.2f')),...
        cellstr(num2str(fQ,'%.3f')),...
        'VariableNames',TableVars);

    ExportData_Path = [ExportSummaryTable_PartialPath,'_',Sites{i},'.csv'];
    writetable(SummaryTable,ExportData_Path);
end