function [Hour,Minute,Second,u,v,w,T,diag] = import_wind(filename, startRow, endRow)
%import_wind Import numeric data from a text file as column vectors.
%   [HOUR,MINUTE,SECOND,U,V,W,T,diag] = import_wind(FILENAME) Reads data
%   from text file FILENAME for the default selection.
%
%   [HOUR,MINUTE,SECOND,U,V,W,T,diag] = import_wind(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [Hour,Minute,Second,u,v,w,T,diag] = import_wind('Oceano_20150515_1140_1210_Wind_S4_z3050mm.txt',2, 90002);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/01/02 12:08:53

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Hour = dataArray{:, 1};
Minute = dataArray{:, 2};
Second = dataArray{:, 3};
u = dataArray{:, 4};
v = dataArray{:, 5};
w = dataArray{:, 6};
T = dataArray{:, 7};
diag = dataArray{:, 8};

